/*=============================================================
  Supply Chain Ontology — Step 2: Create Tables
  =============================================================*/

USE DATABASE SUPPLY_CHAIN_ONTOLOGY;
USE SCHEMA CORE;

-- Master Data: Customers
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER(38,0) NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    SEGMENT       VARCHAR(50),
    REGION        VARCHAR(50),
    COUNTRY       VARCHAR(50),
    CREDIT_LIMIT  NUMBER(12,2),
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Master Data',
    ONTOLOGY_ENTITY   = 'Core Entity',
    SENSITIVITY       = 'Internal'
);

-- Master Data: Suppliers
CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID      NUMBER(38,0) NOT NULL PRIMARY KEY,
    SUPPLIER_NAME    VARCHAR(100),
    CATEGORY         VARCHAR(50),
    COUNTRY          VARCHAR(50),
    REGION           VARCHAR(50),
    LEAD_TIME_DAYS   NUMBER(38,0),
    RELIABILITY_SCORE NUMBER(3,2),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Master Data',
    ONTOLOGY_ENTITY   = 'Core Entity',
    SENSITIVITY       = 'Internal'
);

-- Master Data: Parts
CREATE OR REPLACE TABLE PARTS (
    PART_ID        NUMBER(38,0) NOT NULL PRIMARY KEY,
    PART_NAME      VARCHAR(100),
    PART_CATEGORY  VARCHAR(50),
    UNIT_OF_MEASURE VARCHAR(20),
    STANDARD_COST  NUMBER(10,2),
    WEIGHT_KG      NUMBER(8,3),
    IS_CRITICAL    BOOLEAN
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Master Data',
    ONTOLOGY_ENTITY   = 'Core Entity',
    SENSITIVITY       = 'Internal'
);

-- Operations: Plants
CREATE OR REPLACE TABLE PLANTS (
    PLANT_ID              NUMBER(38,0) NOT NULL PRIMARY KEY,
    PLANT_NAME            VARCHAR(100),
    CITY                  VARCHAR(50),
    COUNTRY               VARCHAR(50),
    REGION                VARCHAR(50),
    CAPACITY_UNITS_PER_DAY NUMBER(38,0),
    PLANT_TYPE            VARCHAR(30)
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Operations',
    ONTOLOGY_ENTITY   = 'Core Entity',
    SENSITIVITY       = 'Internal'
);

-- Bridge: Supplier-Parts
CREATE OR REPLACE TABLE SUPPLIER_PARTS (
    SUPPLIER_ID    NUMBER(38,0) NOT NULL,
    PART_ID        NUMBER(38,0) NOT NULL,
    UNIT_COST      NUMBER(10,2),
    MIN_ORDER_QTY  NUMBER(38,0),
    CONTRACT_START DATE,
    CONTRACT_END   DATE,
    PRIMARY KEY (SUPPLIER_ID, PART_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (PART_ID)     REFERENCES PARTS(PART_ID)
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Supply Chain',
    ONTOLOGY_ENTITY   = 'Bridge Table',
    SENSITIVITY       = 'Confidential'
);

-- Transactions: Orders
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID               NUMBER(38,0) NOT NULL PRIMARY KEY,
    CUSTOMER_ID            NUMBER(38,0),
    ORDER_DATE             DATE,
    REQUESTED_DELIVERY_DATE DATE,
    ORDER_STATUS           VARCHAR(20),
    QUANTITY_ORDERED       NUMBER(38,0),
    QUANTITY_SHIPPED       NUMBER(38,0),
    TOTAL_VALUE            NUMBER(12,2),
    PRIORITY               VARCHAR(10),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Supply Chain',
    ONTOLOGY_ENTITY   = 'Transaction',
    SENSITIVITY       = 'Confidential'
);

-- Transactions: Shipments
CREATE OR REPLACE TABLE SHIPMENTS (
    SHIPMENT_ID            NUMBER(38,0) NOT NULL PRIMARY KEY,
    ORDER_ID               NUMBER(38,0),
    SUPPLIER_ID            NUMBER(38,0),
    PLANT_ID               NUMBER(38,0),
    SHIP_DATE              DATE,
    EXPECTED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE   DATE,
    QUANTITY_SHIPPED       NUMBER(38,0),
    SHIPPING_COST          NUMBER(10,2),
    CUSTOMS_DUTY           NUMBER(10,2),
    HANDLING_FEE           NUMBER(10,2),
    CARRIER                VARCHAR(50),
    SHIPMENT_STATUS        VARCHAR(20),
    FOREIGN KEY (ORDER_ID)    REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (PLANT_ID)    REFERENCES PLANTS(PLANT_ID)
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Supply Chain',
    ONTOLOGY_ENTITY   = 'Transaction',
    SENSITIVITY       = 'Confidential'
);

-- Time Series: Inventory Snapshots
CREATE OR REPLACE TABLE INVENTORY_SNAPSHOTS (
    SNAPSHOT_ID            NUMBER(38,0) NOT NULL PRIMARY KEY,
    PLANT_ID               NUMBER(38,0),
    PART_ID                NUMBER(38,0),
    SNAPSHOT_DATE          DATE,
    QUANTITY_ON_HAND       NUMBER(38,0),
    QUANTITY_RESERVED      NUMBER(38,0),
    QUANTITY_AVAILABLE     NUMBER(38,0),
    DAILY_CONSUMPTION_RATE NUMBER(10,2),
    REORDER_POINT          NUMBER(38,0),
    FOREIGN KEY (PLANT_ID) REFERENCES PLANTS(PLANT_ID),
    FOREIGN KEY (PART_ID)  REFERENCES PARTS(PART_ID)
)
WITH TAG (
    SNOWFLAKE.CORE.CERTIFICATION_STATUS = 'CERTIFIED',
    DATA_DOMAIN       = 'Operations',
    ONTOLOGY_ENTITY   = 'Time Series',
    SENSITIVITY       = 'Internal'
);
